parameters:
#    mazenovi_security.example.class: Mazenovi\SecurityBundle\Example

services:
    mazenovi_security.csrf_token_validation:
        class: Mazenovi\SecurityBundle\EventListener\RequestListener
        tags: 
            - { name: kernel.event_listener, event:kernel.request, method: onKernelRequest, priority: 100 }
        arguments: [@form.csrf_provider, %kernel.environment%]
