parameters:
#    mazenovi_wsse_auth.example.class: Mazenovi\WsseAuthBundle\Example

services:
  wsse.security.authentication.provider:
    class:  Mazenovi\WsseAuthBundle\Security\Authentication\Provider\WsseProvider
    arguments: ['', %security.authentication.login.listener.wsse.nonces_cache_path%, %security.authentication.login.listener.wsse.lifetime%, %kernel.cache_dir%]

  wsse.security.authentication.login.listener:
    class:  Mazenovi\WsseAuthBundle\Security\Authentication\Login\WsseListener
    tags:
        -  { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    arguments: [@security.context, @session]

  wsse.security.firewall.listener:
    class:  Mazenovi\WsseAuthBundle\Security\Firewall\WsseListener
    arguments: [@security.context, @security.authentication.manager]

  wsse.security.firewall.request_matcher:
    class:  Mazenovi\WsseAuthBundle\Security\Firewall\WsseRequestMatcher
    arguments: [%security.authentication.login.listener.wsse.protected_urls%]