fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

mazenovi_user_bundle:
    resource: "@MazenoviUserBundle/Resources/config/routing.yml"
    prefix:   /

mazenovi_todomvc_api:
  resource:  "@MazenoviTodoMVCBundle/Controller/ApiController.php"
  type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc