parameters:
#    mazenovi_tool_box.example.class: Mazenovi\ToolBoxBundle\Example

services:
    mazenovi_tool_box.csrf_token_validation:
        class: Mazenovi\ToolBoxBundle\EventListener\RequestListener
        tags: 
            - { name: kernel.event_listener, event:kernel.request, method: onKernelRequest, priority: 100 }
        arguments: [@form.csrf_provider, %kernel.environment%]
