# http://jmsyst.com/bundles/JMSSerializerBundle/master/reference/yml_reference
# @todo get this file working
Mazenovi\TodoMVCBundle\Model\Todo:
    virual_properties:
        getDisplayName:
            serialized_name: displayName
