parameters:
#    mazenovi_user.example.class: Mazenovi\UserBundle\Example

services:
#    mazenovi_user.example:
#        class: %mazenovi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
